name: Build

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      working-directory: /src/
      run: dotnet build --configuration Release
  
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Test
        working-directory: /src/
        run: dotnet test -- configuration Release
